/**
 * tempo-directory-seed.ts
 * Tempo simulation prospect-directory seed config (Rehearse Essentials).
 * Hand-authored companies drop in via authoredCompanies without code changes.
 */

import { TEMPO_SIMULATION_ID } from "../../lib/constants";
import type {
  FactPoolEntry,
  TempoDirectorySeedConfig,
  TrapSubtype,
} from "../generate-prospect-directory";

function factEntry(text: string, theme: string): FactPoolEntry {
  return { text, theme };
}

const TARGET_TRIGGER_SIGNATURE_THEMES = [
  {
    id: "front_desk_hiring",
    matchers: ["front desk", "front-desk", "receptionist", "reception hire", "desk coordinator"],
  },
  {
    id: "phone_hold_complaints",
    matchers: ["hold time", "hold times", "phone hold", "phones are always busy", "callbacks take"],
  },
];

const DISQUALIFIER_KEYWORDS_BY_TRAP_SUBTYPE: Record<TrapSubtype, string[]> = {
  already_solved: ["sloteasy", "scheduling vendor", "multi-year agreement", "standardized on", "incumbent"],
  franchise_power: ["franchise", "corporate", "mandates", "approved vendor", "vendor list"],
  contracting: ["freeze", "discretionary", "spend freeze", "contracting", "margin protection", "vendor projects"],
  phantom_fit: ["rebranding", "not a new site", "existing location", "rebrand"],
};

const TRAP_DISQUALIFIER_VARIANTS_BY_SUBTYPE: Record<TrapSubtype, string[]> = {
  already_solved: [
    "Signed a multi-year agreement with a scheduling vendor last year.",
    "Front office completed a scheduling software rollout under a multi-year contract eighteen months ago.",
    "Practice-wide vendor selection for appointment software finished last quarter with a locked-in term.",
    "Operations standardized on an incumbent scheduling platform after a competitive review two years ago.",
  ],
  franchise_power: [
    "Corporate franchise office mandates approved vendor lists for all locations.",
    "Franchise agreement requires all clinics to purchase scheduling tools from an approved corporate catalog.",
  ],
  contracting: [
    "Finance memo cites a freeze on discretionary software spend.",
    "CFO memo suspended evaluation of new SaaS vendors through the next budget cycle.",
    "Leadership circulated a directive pausing all non-essential vendor contracts until fiscal year end.",
  ],
  phantom_fit: [
    "Expansion headline was a rebranding of an existing location, not a new site opening.",
    "Announced 'new clinic' was a renamed existing office; no additional site was added.",
  ],
};

function blurbLengthBucket(blurb: string): string {
  const length = blurb.trim().length;
  if (length < 80) {
    return "short";
  }
  if (length <= 150) {
    return "medium";
  }
  return "long";
}

const TEMPO_STRUCTURAL_CORRELATION: TempoDirectorySeedConfig["structuralCorrelation"] = {
  getClass: (company) => company.class,
  exemptPropertyNames: [],
  properties: [
    { name: "research_facts length", getValue: (company) => company.researchFacts.length },
    { name: "public_signals length", getValue: (company) => company.publicSignals.length },
    {
      name: "contact count",
      getValue: (company) => (company.contactSet ? 1 + company.contactSet.traps.length : 3),
    },
    { name: "blurb length bucket", getValue: (company) => blurbLengthBucket(company.blurb) },
    {
      name: "size_note presence",
      getValue: (company) => (company.sizeNote.trim().length > 0 ? "has" : "none"),
    },
  ],
};

const RESEARCH_FACTS_BY_VERTICAL: Record<string, FactPoolEntry[]> = {
  dental: [
    factEntry("Careers page lists hygienist openings at two locations.", "careers_hygienist"),
    factEntry("Google reviews praise friendly staff with occasional wait-time mentions.", "google_wait"),
    factEntry("Local newsletter profiled the practice's school outreach program.", "newsletter_outreach"),
    factEntry("Website highlights same-day emergency appointment availability.", "website_emergency"),
    factEntry("Patient forum threads discuss parking at the downtown location.", "forum_parking"),
    factEntry("Chamber of commerce spotlighted the group's charity dental day.", "chamber_charity"),
    factEntry("Indeed listing seeks a dental assistant for the west clinic.", "indeed_assistant"),
    factEntry("Blog post explained the group's approach to pediatric patient comfort.", "blog_pediatric"),
    factEntry("Facebook post promoted a free oral-health screening at a community fair.", "social_screening"),
    factEntry("Trade publication noted the practice's participation in a regional dental association.", "trade_association"),
    factEntry("Yelp reviewers mention convenient Saturday morning hours.", "yelp_hours"),
    factEntry("Website FAQ describes accepted insurance plans by location.", "website_insurance"),
    factEntry("Local paper covered a ribbon-cutting at a renovated waiting area.", "press_renovation"),
    factEntry("Instagram story featured staff volunteering at a health fair.", "instagram_volunteer"),
    factEntry("Patient portal help page was updated with new contact instructions.", "portal_update"),
    factEntry("Careers site advertises a sterilization technician role.", "careers_sterilization"),
    factEntry("Google reviews highlight gentle hygienists and clear billing explanations.", "google_hygienists"),
    factEntry("Community calendar listed a free dental-sealant clinic for teens.", "community_sealant"),
  ],
  veterinary: [
    factEntry("Job board shows a part-time kennel attendant role at the north clinic.", "careers_kennel"),
    factEntry("Yelp reviews mention compassionate care and weekend hours.", "yelp_weekend"),
    factEntry("Press release covered a pet adoption event hosted at one location.", "press_adoption"),
    factEntry("Social posts show updated signage after a minor lobby renovation.", "social_lobby"),
    factEntry("Trade blog noted the group's partnership with a regional animal shelter.", "trade_shelter"),
    factEntry("Website lists vaccination clinic dates for the spring season.", "website_vaccination"),
    factEntry("Google reviews praise thorough exam explanations from veterinarians.", "google_exams"),
    factEntry("Local magazine featured the hospital's wildlife rehabilitation fundraiser.", "magazine_wildlife"),
    factEntry("Indeed post seeks a veterinary technician for evening shifts.", "indeed_vet_tech"),
    factEntry("Facebook event promoted a low-cost microchip clinic.", "social_microchip"),
    factEntry("Blog article discussed seasonal allergy care for dogs.", "blog_allergies"),
    factEntry("Chamber directory entry highlights the group's boarding services.", "chamber_boarding"),
    factEntry("Patient forum threads recommend the urgent-care wing for minor injuries.", "forum_urgent"),
    factEntry("Instagram reel showed a behind-the-scenes tour of the surgical suite.", "instagram_surgical"),
    factEntry("Careers page lists a client service representative opening.", "careers_client_service"),
    factEntry("Google reviews mention easy online prescription refill requests.", "google_prescriptions"),
    factEntry("Local paper profiled the chief veterinarian's community lecture series.", "press_lecture"),
    factEntry("Website FAQ explains new-patient paperwork requirements.", "website_paperwork"),
  ],
  "physical therapy": [
    factEntry("Careers site advertises a new patient coordinator role.", "careers_coordinator"),
    factEntry("Reviews cite short intake paperwork and helpful front-desk staff.", "reviews_intake"),
    factEntry("Clinic blog published tips for post-surgery rehab at home.", "blog_rehab"),
    factEntry("Local paper mentioned expanded evening appointment blocks.", "press_evening"),
    factEntry("Website lists insurance partners accepted at all sites.", "website_insurance"),
    factEntry("Google reviews highlight knowledgeable therapists and clean treatment rooms.", "google_therapists"),
    factEntry("Indeed listing seeks a physical therapy aide.", "indeed_aide"),
    factEntry("Facebook post promoted a free injury-prevention workshop.", "social_workshop"),
    factEntry("Chamber newsletter featured the group's sports-medicine partnership.", "chamber_sports"),
    factEntry("Patient forum discussed parking options near the main clinic.", "forum_parking"),
    factEntry("Instagram story showed equipment upgrades in the gym area.", "instagram_equipment"),
    factEntry("Trade blog noted the clinic's telehealth consult pilot.", "trade_telehealth"),
    factEntry("Yelp reviewers mention flexible morning appointment slots.", "yelp_morning"),
    factEntry("Website FAQ describes what to wear for a first visit.", "website_first_visit"),
    factEntry("Local magazine listed the clinic in a best-of rehab roundup.", "magazine_roundup"),
    factEntry("Careers page lists a billing specialist for the billing office.", "careers_billing"),
    factEntry("Google reviews praise clear home-exercise handouts.", "google_handouts"),
    factEntry("Community board listed a posture-screening event at a farmers market.", "community_posture"),
  ],
  optometry: [
    factEntry("Indeed listing seeks an optical lab technician.", "indeed_lab"),
    factEntry("Google reviews highlight frame selection and quick eye exams.", "google_frames"),
    factEntry("Facebook post promoted a back-to-school vision screening drive.", "social_screening"),
    factEntry("Website notes complimentary frame adjustments during business hours.", "website_adjustments"),
    factEntry("Chamber of commerce spotlighted the group's downtown storefront.", "chamber_storefront"),
    factEntry("Careers page lists an optician trainee position.", "careers_optician"),
    factEntry("Instagram campaign featured new designer frame arrivals.", "instagram_frames"),
    factEntry("Local paper covered a donation of exam vouchers to a school district.", "press_donation"),
    factEntry("Yelp reviewers mention helpful staff explaining lens options.", "yelp_lens"),
    factEntry("Blog post explained the difference between medical and routine eye exams.", "blog_exams"),
    factEntry("Google reviews praise short wait times for contact-lens fittings.", "google_contacts"),
    factEntry("Trade publication noted the group's participation in a vision-health fair.", "trade_fair"),
    factEntry("Website FAQ lists accepted vision insurance carriers.", "website_vision_insurance"),
    factEntry("Patient forum thread discussed parking at the mall location.", "forum_mall_parking"),
    factEntry("Social post highlighted a senior-discount frame promotion.", "social_senior"),
    factEntry("Careers site advertises a retail associate for the optical boutique.", "careers_retail"),
    factEntry("Local lifestyle magazine included the brand in a downtown shopping guide.", "magazine_shopping"),
    factEntry("Google reviews mention thorough glaucoma screening explanations.", "google_glaucoma"),
  ],
  "med spa": [
    factEntry("Instagram campaign featured seasonal skincare packages.", "instagram_skincare"),
    factEntry("Reviews praise consultative staff and spa-like waiting areas.", "reviews_consultative"),
    factEntry("Hiring page lists a guest coordinator for the flagship studio.", "careers_guest"),
    factEntry("Local lifestyle magazine included the brand in a wellness roundup.", "magazine_wellness"),
    factEntry("Website FAQ notes online intake forms for first-time clients.", "website_intake"),
    factEntry("Google reviews highlight relaxing treatment rooms and attentive staff.", "google_relaxing"),
    factEntry("Facebook event promoted a free skin-analysis day.", "social_skin_analysis"),
    factEntry("Indeed post seeks a licensed esthetician for weekend shifts.", "indeed_esthetician"),
    factEntry("Blog article discussed pre-treatment preparation for laser services.", "blog_laser"),
    factEntry("Chamber spotlight noted the studio's charity fundraiser for women's health.", "chamber_health"),
    factEntry("Yelp reviewers mention easy online booking for consultations.", "yelp_booking"),
    factEntry("Trade blog covered the group's new membership loyalty program.", "trade_loyalty"),
    factEntry("Website lists provider credentials and certification badges.", "website_credentials"),
    factEntry("Patient forum discussed parking validation at the retail center.", "forum_parking"),
    factEntry("Instagram reel showcased a new injectable treatment menu.", "instagram_injectable"),
    factEntry("Local paper profiled the medical director's community lecture.", "press_director"),
    factEntry("Google reviews praise discreet check-in and private treatment suites.", "google_privacy"),
    factEntry("Careers page lists a spa attendant for the relaxation lounge.", "careers_attendant"),
  ],
  chiropractic: [
    factEntry("Careers page lists a chiropractic assistant opening.", "careers_assistant"),
    factEntry("Reviews mention convenient parking and flexible morning hours.", "reviews_parking"),
    factEntry("Blog post explained the group's approach to sports injury rehab.", "blog_sports"),
    factEntry("Community calendar listed a free posture workshop at one clinic.", "community_workshop"),
    factEntry("Website promotes new-patient specials without mentioning scheduling tools.", "website_specials"),
    factEntry("Google reviews highlight thorough initial evaluations.", "google_evaluations"),
    factEntry("Indeed listing seeks a front-office team member.", "indeed_front_office"),
    factEntry("Facebook post promoted a workplace ergonomics seminar.", "social_ergonomics"),
    factEntry("Local newsletter featured the practice's youth-athlete outreach.", "newsletter_athlete"),
    factEntry("Yelp reviewers mention short visits for maintenance adjustments.", "yelp_maintenance"),
    factEntry("Instagram story showed updated traction equipment.", "instagram_traction"),
    factEntry("Chamber directory notes the clinic's wellness talk series.", "chamber_wellness"),
    factEntry("Website FAQ describes what imaging patients should bring.", "website_imaging"),
    factEntry("Trade blog noted the group's referral partnership with a local gym.", "trade_gym"),
    factEntry("Google reviews praise clear explanations of treatment plans.", "google_plans"),
    factEntry("Patient forum discussed which location has the easiest highway access.", "forum_access"),
    factEntry("Careers site advertises a billing coordinator role.", "careers_billing"),
    factEntry("Local paper covered a ribbon-cutting at a second location.", "press_second_location"),
  ],
  retail: [
    factEntry("Store locator shows six locations across the Mountain West.", "store_locator"),
    factEntry("Indeed posts highlight seasonal floor staff hiring.", "indeed_seasonal"),
    factEntry("Local business journal covered a holiday inventory expansion.", "journal_inventory"),
    factEntry("Google reviews mention helpful associates and easy returns.", "google_returns"),
    factEntry("Facebook event promoted a warehouse sale at the flagship store.", "social_warehouse"),
    factEntry("Website highlights extended holiday shopping hours.", "website_holiday_hours"),
    factEntry("Chamber newsletter featured the retailer's downtown job fair.", "chamber_job_fair"),
    factEntry("Instagram post showcased new product displays for spring.", "instagram_displays"),
    factEntry("Yelp reviewers mention organized aisles and knowledgeable staff.", "yelp_aisles"),
    factEntry("Press release announced a partnership with a regional outdoor brand.", "press_partnership"),
    factEntry("Careers page lists a stockroom associate opening.", "careers_stockroom"),
    factEntry("Google reviews praise the loyalty rewards program.", "google_rewards"),
    factEntry("Local paper covered a community donation drive hosted in-store.", "paper_donation"),
    factEntry("Website FAQ describes curbside pickup availability.", "website_curbside"),
    factEntry("Trade blog noted the chain's expanded camping gear selection.", "trade_camping"),
    factEntry("Facebook post highlighted a manager's choice end-cap promotion.", "social_endcap"),
    factEntry("Indeed listing seeks a visual merchandising coordinator.", "indeed_merchandising"),
    factEntry("Google reviews mention clean fitting rooms and fast checkout.", "google_checkout"),
  ],
  hospitality: [
    factEntry("Travel blog review praised renovated guest rooms and lobby Wi-Fi.", "blog_renovation"),
    factEntry("Indeed listing seeks a night front-desk supervisor.", "indeed_night_desk"),
    factEntry("TripAdvisor thread discusses breakfast buffet hours.", "tripadvisor_breakfast"),
    factEntry("Press mention covered a summer patio reopening.", "press_patio"),
    factEntry("Website advertises group booking discounts for corporate retreats.", "website_group"),
    factEntry("Google reviews highlight comfortable beds and mountain views.", "google_beds"),
    factEntry("Instagram post featured a local-artist lobby installation.", "instagram_art"),
    factEntry("Careers page lists a housekeeping team lead role.", "careers_housekeeping"),
    factEntry("Chamber spotlight noted the property's conference-room upgrades.", "chamber_conference"),
    factEntry("Yelp reviewers mention friendly concierge recommendations.", "yelp_concierge"),
    factEntry("Facebook event promoted a holiday brunch package.", "social_brunch"),
    factEntry("Local magazine listed the lodge in a ski-season stay guide.", "magazine_ski"),
    factEntry("Website FAQ describes pet-friendly room policies.", "website_pets"),
    factEntry("Google reviews praise quick check-in at the front desk.", "google_checkin"),
    factEntry("Trade publication noted the hotel's sustainability certification.", "trade_sustainability"),
    factEntry("Indeed post seeks a banquet setup attendant.", "indeed_banquet"),
    factEntry("Press release announced a partnership with a regional tour operator.", "press_tours"),
    factEntry("Instagram story showed refreshed pool-deck furniture.", "instagram_pool"),
  ],
  "auto repair": [
    factEntry("Google reviews cite transparent estimates and shuttle service.", "google_estimates"),
    factEntry("Careers page lists a service advisor trainee role.", "careers_advisor"),
    factEntry("Local radio spot promoted a fall maintenance special.", "radio_maintenance"),
    factEntry("Website shows Saturday hours at two neighborhood shops.", "website_saturday"),
    factEntry("Chamber directory notes ASE-certified technicians on staff.", "chamber_ase"),
    factEntry("Indeed listing seeks an automotive technician apprentice.", "indeed_technician"),
    factEntry("Facebook post highlighted a free battery-check event.", "social_battery"),
    factEntry("Yelp reviewers mention honest diagnostics and fair pricing.", "yelp_diagnostics"),
    factEntry("Blog article explained when to replace winter tires in mountain climates.", "blog_tires"),
    factEntry("Google reviews praise loaner-car availability during repairs.", "google_loaner"),
    factEntry("Local paper covered a shop expansion into a second bay.", "press_expansion"),
    factEntry("Website FAQ lists OEM and aftermarket parts options.", "website_parts"),
    factEntry("Instagram reel showed a same-day brake-service promotion.", "instagram_brakes"),
    factEntry("Trade blog noted the group's fleet-service contract wins.", "trade_fleet"),
    factEntry("Careers site advertises a parts counter representative.", "careers_parts"),
    factEntry("Google reviews mention clean waiting areas with complimentary coffee.", "google_waiting"),
    factEntry("Chamber newsletter featured the shop's high-school internship program.", "chamber_internship"),
    factEntry("Press mention covered a community car-care clinic for seniors.", "press_seniors"),
  ],
  "legal services": [
    factEntry("Firm blog published a guide to small-business contract basics.", "blog_contracts"),
    factEntry("LinkedIn post announced an associate attorney hire.", "linkedin_associate"),
    factEntry("Website lists practice areas without operational software mentions.", "website_practice"),
    factEntry("Google reviews mention responsive paralegal support.", "google_paralegal"),
    factEntry("Bar association newsletter featured the firm's pro-bono clinic.", "bar_probono"),
    factEntry("Indeed listing seeks a legal assistant for the litigation team.", "indeed_legal_assistant"),
    factEntry("Facebook post promoted a free estate-planning seminar.", "social_estate"),
    factEntry("Chamber directory highlights the firm's business-law focus.", "chamber_business"),
    factEntry("Yelp reviewers mention clear fee explanations at consultation.", "yelp_fees"),
    factEntry("Website FAQ describes document-upload options for clients.", "website_upload"),
    factEntry("Local paper profiled a partner's appointment to a civic board.", "press_civic"),
    factEntry("Google reviews praise timely callback from intake staff.", "google_callback"),
    factEntry("Trade publication noted the firm's expansion into employment law.", "trade_employment"),
    factEntry("Instagram post highlighted a scholarship fund for law students.", "instagram_scholarship"),
    factEntry("Careers page lists a receptionist for the main office.", "careers_reception"),
    factEntry("Blog article explained recent changes to local zoning appeals.", "blog_zoning"),
    factEntry("Bar journal mentioned the firm's mentorship program.", "bar_mentorship"),
    factEntry("Google reviews highlight organized case updates from paralegals.", "google_case_updates"),
  ],
  "fitness studio": [
    factEntry("Instagram promoted a six-week beginner strength program.", "instagram_strength"),
    factEntry("Indeed listing seeks part-time front-desk staff for early shifts.", "indeed_front_desk"),
    factEntry("Google reviews highlight clean facilities and class variety.", "google_facilities"),
    factEntry("Local magazine listed the studio in a best-of fitness roundup.", "magazine_fitness"),
    factEntry("Website shows class schedules and intro membership offers.", "website_classes"),
    factEntry("Facebook event promoted a free outdoor boot-camp trial.", "social_bootcamp"),
    factEntry("Yelp reviewers mention motivating instructors and good music.", "yelp_instructors"),
    factEntry("Careers page lists a group-fitness instructor opening.", "careers_instructor"),
    factEntry("Blog post explained the studio's recovery-room amenities.", "blog_recovery"),
    factEntry("Chamber spotlight noted the brand's corporate wellness partnerships.", "chamber_corporate"),
    factEntry("Google reviews praise easy class booking through the member app.", "google_app"),
    factEntry("Press mention covered a charity ride event at the studio.", "press_charity_ride"),
    factEntry("Website FAQ describes towel service and locker policies.", "website_lockers"),
    factEntry("Instagram story featured new rowing machines on the floor.", "instagram_rowing"),
    factEntry("Trade blog noted the studio's expanded youth athletic program.", "trade_youth"),
    factEntry("Indeed post seeks a membership sales coordinator.", "indeed_membership"),
    factEntry("Local paper profiled the founder's mountain-race sponsorship.", "press_sponsorship"),
    factEntry("Google reviews mention friendly staff at the front desk.", "google_front_desk"),
  ],
  "property management": [
    factEntry("Careers page lists a leasing coordinator for a portfolio of units.", "careers_leasing"),
    factEntry("Google reviews mention responsive maintenance ticketing.", "google_maintenance"),
    factEntry("Press release covered acquisition of a twelve-unit apartment block.", "press_acquisition"),
    factEntry("Website FAQ describes tenant portal features for rent payments.", "website_portal"),
    factEntry("Local real-estate blog profiled the firm's resident events program.", "blog_resident_events"),
    factEntry("Indeed listing seeks a property inspector for the portfolio.", "indeed_inspector"),
    factEntry("Facebook post promoted a spring landscaping refresh at several complexes.", "social_landscaping"),
    factEntry("Yelp reviewers mention professional on-site management staff.", "yelp_management"),
    factEntry("Chamber newsletter featured the firm's affordable-housing initiative.", "chamber_housing"),
    factEntry("Website lists available floor plans for downtown rentals.", "website_floorplans"),
    factEntry("Google reviews praise clear lease-renewal communication.", "google_lease"),
    factEntry("Trade publication noted the group's energy-efficiency retrofit program.", "trade_energy"),
    factEntry("Instagram post highlighted a resident appreciation barbecue.", "instagram_barbecue"),
    factEntry("Careers site advertises a maintenance technician role.", "careers_maintenance"),
    factEntry("Local paper covered a ribbon-cutting at a new townhome community.", "press_townhomes"),
    factEntry("Blog article explained the firm's pet-policy updates.", "blog_pets"),
    factEntry("Google reviews mention well-kept common areas and landscaping.", "google_common_areas"),
    factEntry("Chamber directory entry lists the firm's commercial-property division.", "chamber_commercial"),
  ],
  "urgent care": [
    factEntry("Website lists weekend walk-in hours by location.", "website_weekend"),
    factEntry("Indeed post seeks medical receptionists for evening shifts.", "indeed_reception"),
    factEntry("Google reviews mention short visits for minor injuries.", "google_short_visits"),
    factEntry("Health-system partnership press release noted shared branding.", "press_branding"),
    factEntry("Patient forum discussed parking at the newest walk-in clinic.", "forum_parking"),
    factEntry("Careers page lists a radiology technician opening.", "careers_radiology"),
    factEntry("Facebook post promoted a flu-shot clinic schedule.", "social_flu"),
    factEntry("Yelp reviewers mention clean exam rooms and courteous staff.", "yelp_exam_rooms"),
    factEntry("Local paper profiled the clinic's occupational-health contract wins.", "press_occupational"),
    factEntry("Website FAQ describes accepted insurance and self-pay options.", "website_insurance"),
    factEntry("Instagram story showed updated triage signage.", "instagram_triage"),
    factEntry("Trade blog noted expanded telehealth follow-up visits.", "trade_telehealth_uc"),
    factEntry("Google reviews praise clear discharge instructions.", "google_discharge"),
    factEntry("Chamber spotlight listed the clinic in a healthcare directory.", "chamber_directory"),
    factEntry("Careers site advertises a lab assistant for the on-site lab.", "careers_lab"),
    factEntry("Blog post explained when to choose urgent care over the ER.", "blog_er_guidance"),
    factEntry("Press mention covered a partnership with a local employer for on-site care.", "press_employer"),
    factEntry("Google reviews highlight convenient highway access.", "google_access"),
  ],
};

const VERTICAL_ENTITY_LABEL: Record<string, string> = {
  dental: "practice",
  veterinary: "hospital",
  "physical therapy": "clinic",
  optometry: "office",
  "med spa": "studio",
  chiropractic: "clinic",
  retail: "store",
  hospitality: "property",
  "auto repair": "shop",
  "legal services": "firm",
  "fitness studio": "studio",
  "property management": "portfolio",
  "urgent care": "clinic",
};

const SUPPLEMENTAL_FACT_THEMES = [
  "community open house",
  "staff volunteer day",
  "seasonal hours update",
  "local press profile",
  "customer appreciation event",
  "facility refresh project",
  "industry award mention",
  "neighborhood partnership",
  "employee training program",
  "charity fundraiser",
  "open-enrollment reminder",
  "sustainability initiative",
  "patient education series",
  "member appreciation week",
  "regional trade feature",
] as const;

function buildSupplementalFacts(vertical: string): FactPoolEntry[] {
  const entity = VERTICAL_ENTITY_LABEL[vertical] ?? "business";
  return SUPPLEMENTAL_FACT_THEMES.map((theme, index) =>
    factEntry(
      `Local coverage noted the ${entity}'s ${theme} in the Mountain West region.`,
      `supplement_${index}`
    )
  );
}

const MERGED_RESEARCH_FACTS_BY_VERTICAL: Record<string, FactPoolEntry[]> = Object.fromEntries(
  Object.entries(RESEARCH_FACTS_BY_VERTICAL).map(([vertical, entries]) => [
    vertical,
    [...entries, ...buildSupplementalFacts(vertical)],
  ])
);

const PUBLIC_SIGNALS_BY_VERTICAL: Record<string, string[]> = {
  dental: [
    "Expanded hygiene team hiring at two locations",
    "Local paper covered a community dental-health day",
    "Website refresh highlighting family appointment blocks",
    "Ribbon-cutting for a renovated patient waiting area",
    "Social post promoting back-to-school checkup reminders",
    "Careers page lists dental assistant openings",
    "Chamber feature on the group's charity outreach",
    "Google review theme: friendly hygienists",
    "New patient welcome packet highlighted on the website",
    "Trade mention of participation in a regional dental association",
    "Job listing: Dental Assistant — East Clinic",
    "Press clip on a free screening event at a community center",
    "Instagram post showcasing updated operatory equipment",
    "Review theme: easy online intake forms",
    "Local newsletter noted steady multi-site operations",
  ],
  veterinary: [
    "Weekend urgent-care hours advertised on the website",
    "Job listing: Veterinary Technician",
    "Press coverage of a pet adoption fundraiser",
    "Social campaign for spring vaccination clinics",
    "Google review theme: compassionate veterinarians",
    "New boarding wing mentioned in a local magazine",
    "Careers page lists kennel attendant openings",
    "Chamber spotlight on wildlife rehabilitation support",
    "Facebook event for a low-cost microchip day",
    "Review theme: thorough exam explanations",
    "Trade blog mention of shelter partnership events",
    "Website highlights telehealth triage for pet owners",
    "Local paper profiled the chief veterinarian's lecture series",
    "Instagram reel of a behind-the-scenes surgical tour",
    "Job board post for a client service representative",
  ],
  "physical therapy": [
    "Evening appointment blocks added at the main clinic",
    "Job listing: Physical Therapy Aide",
    "Blog promotion of a free injury-prevention workshop",
    "Google review theme: knowledgeable therapists",
    "Careers page lists a patient coordinator role",
    "Chamber note on a sports-medicine partnership",
    "Website lists expanded insurance partners",
    "Local magazine included the clinic in a rehab roundup",
    "Facebook post about new gym equipment",
    "Review theme: helpful front-desk intake staff",
    "Trade mention of a telehealth consult pilot",
    "Instagram story highlighting post-surgery rehab tips",
    "Press clip on a posture-screening farmers-market booth",
    "Job listing: Billing Specialist",
    "Community board listing for a wellness talk series",
  ],
  optometry: [
    "Back-to-school vision screening drive announced",
    "Job listing: Optical Lab Technician",
    "Google review theme: wide frame selection",
    "Instagram campaign for new designer arrivals",
    "Chamber spotlight on the downtown storefront",
    "Website notes complimentary frame adjustments",
    "Local paper covered exam-voucher donations to schools",
    "Careers page lists optician trainee openings",
    "Facebook post on a senior-discount frame promotion",
    "Review theme: helpful lens-option explanations",
    "Trade mention of a regional vision-health fair",
    "Blog post explaining medical vs routine eye exams",
    "Press clip on glaucoma-screening awareness month",
    "Job listing: Retail Associate — Optical Boutique",
    "Social post highlighting contact-lens promotion",
  ],
  "med spa": [
    "Seasonal skincare package promotion on Instagram",
    "Job listing: Licensed Esthetician",
    "Google review theme: spa-like waiting areas",
    "Website highlights online intake for new clients",
    "Local lifestyle magazine wellness roundup inclusion",
    "Facebook event for a free skin-analysis day",
    "Careers page lists a guest coordinator role",
    "Chamber feature on a women's-health fundraiser",
    "Review theme: consultative treatment staff",
    "Blog article on laser-treatment preparation",
    "Instagram reel showcasing new injectable menu",
    "Trade mention of a membership loyalty program",
    "Press profile of the medical director's community talk",
    "Job listing: Spa Attendant",
    "Social post on provider credential highlights",
  ],
  chiropractic: [
    "Free posture workshop listed on the community calendar",
    "Job listing: Chiropractic Assistant",
    "Google review theme: flexible morning hours",
    "Website promotes new-patient specials",
    "Facebook seminar on workplace ergonomics",
    "Careers page lists a front-office team member role",
    "Local newsletter on youth-athlete outreach",
    "Review theme: thorough initial evaluations",
    "Instagram story showing updated traction equipment",
    "Chamber directory note on a wellness talk series",
    "Blog post on sports-injury rehab approach",
    "Press clip on a second-location ribbon-cutting",
    "Job listing: Billing Coordinator",
    "Trade mention of a local gym referral partnership",
    "Community event listing for a spinal-health screening",
  ],
  retail: [
    "Seasonal floor-staff hiring on Indeed",
    "Google review theme: helpful associates",
    "Facebook warehouse sale at the flagship store",
    "Local journal clip on holiday inventory expansion",
    "Website highlights extended holiday hours",
    "Chamber feature on a downtown job fair",
    "Instagram post on spring product displays",
    "Review theme: organized aisles",
    "Press release on an outdoor-brand partnership",
    "Careers page lists stockroom associate openings",
    "Trade blog note on expanded camping gear",
    "Social post on a manager's choice promotion",
    "Job listing: Visual Merchandising Coordinator",
    "Google review theme: fast checkout",
    "Community donation drive hosted in-store",
  ],
  hospitality: [
    "Summer patio reopening mentioned in local press",
    "Job listing: Night Front-Desk Supervisor",
    "TripAdvisor thread on breakfast buffet hours",
    "Google review theme: comfortable beds",
    "Website advertises corporate retreat packages",
    "Instagram feature of a lobby art installation",
    "Careers page lists housekeeping team lead role",
    "Chamber note on conference-room upgrades",
    "Review theme: friendly concierge tips",
    "Facebook promotion of a holiday brunch package",
    "Local magazine ski-season stay guide inclusion",
    "Press release on a tour-operator partnership",
    "Job listing: Banquet Setup Attendant",
    "Trade mention of sustainability certification",
    "Social post on refreshed pool-deck furniture",
  ],
  "auto repair": [
    "Saturday hours posted for two neighborhood shops",
    "Job listing: Service Advisor Trainee",
    "Google review theme: transparent estimates",
    "Local radio spot on a fall maintenance special",
    "Chamber note on ASE-certified technicians",
    "Facebook free battery-check event",
    "Review theme: honest diagnostics",
    "Press clip on a second-bay shop expansion",
    "Website FAQ on OEM vs aftermarket parts",
    "Instagram reel on a brake-service promotion",
    "Careers page lists parts counter representative",
    "Trade mention of fleet-service contract wins",
    "Job listing: Automotive Technician Apprentice",
    "Google review theme: loaner cars during repairs",
    "Community car-care clinic for seniors",
  ],
  "legal services": [
    "Associate attorney hire announced on LinkedIn",
    "Google review theme: responsive paralegal support",
    "Bar association feature on a pro-bono clinic",
    "Website lists business-law practice areas",
    "Facebook promotion of a free estate-planning seminar",
    "Job listing: Legal Assistant — Litigation",
    "Chamber directory highlight on business-law focus",
    "Blog guide to small-business contract basics",
    "Review theme: clear consultation fees",
    "Press profile of a partner's civic-board appointment",
    "Trade mention of employment-law expansion",
    "Instagram post on a law-student scholarship fund",
    "Careers page lists main-office receptionist role",
    "Bar journal note on a mentorship program",
    "Community seminar on local zoning appeals",
  ],
  "fitness studio": [
    "Six-week beginner strength program on Instagram",
    "Job listing: Group Fitness Instructor",
    "Google review theme: clean facilities",
    "Local magazine best-of fitness listing",
    "Website shows intro membership offers",
    "Facebook free outdoor boot-camp trial",
    "Review theme: motivating instructors",
    "Careers page lists membership sales coordinator",
    "Press clip on a charity ride event",
    "Blog post on recovery-room amenities",
    "Chamber note on corporate wellness partnerships",
    "Instagram story featuring new rowing machines",
    "Job listing: Part-Time Front-Desk Staff",
    "Trade mention of expanded youth athletic program",
    "Social post on member-app class booking",
  ],
  "property management": [
    "Leasing coordinator role posted on careers page",
    "Google review theme: responsive maintenance",
    "Press release on a twelve-unit acquisition",
    "Website FAQ on tenant rent-payment portal",
    "Real-estate blog on resident events program",
    "Job listing: Property Inspector",
    "Facebook post on spring landscaping refresh",
    "Review theme: professional on-site staff",
    "Chamber feature on affordable-housing initiative",
    "Website lists downtown rental floor plans",
    "Trade note on energy-efficiency retrofits",
    "Instagram resident appreciation barbecue",
    "Careers page lists maintenance technician role",
    "Press clip on a new townhome ribbon-cutting",
    "Blog post explaining updated pet policies",
  ],
  "urgent care": [
    "Weekend walk-in hours listed by location",
    "Job listing: Medical Receptionist — Evenings",
    "Google review theme: short visits for minor injuries",
    "Health-system branding partnership press release",
    "Facebook promotion of flu-shot clinic dates",
    "Careers page lists radiology technician opening",
    "Review theme: clean exam rooms",
    "Local paper on occupational-health contract wins",
    "Website FAQ on insurance and self-pay",
    "Instagram updated triage signage",
    "Trade mention of telehealth follow-up visits",
    "Chamber healthcare directory listing",
    "Job listing: Lab Assistant",
    "Blog post on urgent care vs ER guidance",
    "Press mention of employer on-site care partnership",
  ],
};

const PUBLIC_SIGNALS_BY_TRAP_SUBTYPE: Record<TrapSubtype, string[]> = {
  already_solved: [
    "Website advertises online self-scheduling",
    "Marketing push for refreshed patient portal branding",
    "Google review theme: easy digital check-in",
    "Social post promoting mobile appointment reminders",
    "Careers page lists hygienist openings only",
    "Press clip on a community health fair sponsorship",
    "Review theme: friendly front-office staff",
    "Website highlights same-day emergency slots",
    "Chamber feature on school outreach program",
    "Instagram story on renovated waiting area",
    "Job listing: Dental Assistant",
    "Local newsletter on steady multi-site operations",
    "Blog post on pediatric patient comfort initiatives",
    "Trade mention of regional dental association membership",
    "Facebook post on charity dental day",
  ],
  franchise_power: [
    "Press coverage of a new flagship location opening",
    "Regional business journal profiled growth strategy",
    "Social campaign highlighting expanded service menu",
    "Website refresh promoting brand-wide patient experience standards",
    "Chamber feature on multi-market expansion",
    "Careers page lists clinic manager openings",
    "Google review theme: consistent care quality across locations",
    "Trade blog on centralized clinical training programs",
    "Instagram post celebrating a regional provider award",
    "Local paper on a new market entry announcement",
    "Review theme: modern facilities at newest site",
    "Facebook highlight of uniform branding rollout",
    "Job listing: Regional Operations Coordinator",
    "Press clip on a partnership with a regional health system",
    "Website notes standardized patient intake process",
  ],
  contracting: [
    "Announced administrative staff reductions",
    "Leadership memo excerpt on margin protection",
    "Hiring freeze on non-clinical roles in local newsletter",
    "Press clip on back-office consolidation efforts",
    "Careers page shows only clinical role openings",
    "Google review theme: steady appointment availability",
    "Chamber mention of cost-discipline initiatives",
    "Social post on operational efficiency campaign",
    "Website highlights same-day scheduling windows",
    "Trade blog on centralized purchasing controls",
    "Job listing: Hygienist — South Clinic",
    "Local paper on lease renegotiation at headquarters",
    "Review theme: professional clinical staff",
    "Instagram story on equipment maintenance rather than upgrades",
    "Blog post on fiscal-year planning priorities",
  ],
  phantom_fit: [
    "Press release about a 'new location' opening",
    "Social post celebrating growth milestone",
    "Website banner promoting an additional site",
    "Local paper covered a ribbon-cutting event",
    "Chamber feature on footprint expansion",
    "Google review theme: welcoming new patients",
    "Careers page lists front-office staff for a 'new' clinic",
    "Instagram reel of a refreshed storefront",
    "Job listing: Office Manager — New Site",
    "Facebook event for a grand-opening open house",
    "Review theme: convenient neighborhood access",
    "Trade mention of market share growth",
    "Blog post on meeting community demand",
    "Press clip on hiring for a rebranded location",
    "Website locator adds a pin in an existing market",
  ],
};

const PASS_SUFFIX_BY_VERTICAL: Record<string, string[]> = {
  retail: ["Outfitters", "Supply Co.", "Trading", "Goods", "Market"],
  hospitality: ["Lodging", "Hospitality", "Bistro", "Inn"],
  "auto repair": ["Motors", "Auto Works", "Garage", "Repair"],
  "legal services": ["Legal", "Law Group", "Attorneys"],
  "fitness studio": ["Fitness", "Studio", "Athletics"],
  "property management": ["Properties", "Realty", "Residential"],
};

export const tempoDirectorySeed: TempoDirectorySeedConfig = {
  simulationId: TEMPO_SIMULATION_ID,
  corePainDepartment: "Operations",
  generationPlan: {
    strong_fit: 9,
    near_miss: 16,
    trap: 7,
    pass: 32,
  },
  authoredCompanies: [
    {
      companyName: "Summit Dental Group",
      vertical: "dental",
      locations: 8,
      metro: "Front Range, CO",
      inTerritory: true,
      sizeNote: "8 locations across the Front Range",
      onlineBooking: false,
      blurb:
        "Multi-location dental group scaling appointment volume across Colorado front-range markets.",
      publicSignals: [
        "Opened 8th location three months ago",
        "Job listing: Front Desk Coordinator",
        "Review theme: long phone hold times",
      ],
      researchFacts: [
        "Patient reviews repeatedly mention phones are always busy and callbacks take hours.",
        "Local business journal covered the 8th-location opening and noted scheduling strain at the front desk.",
        "Careers page lists front-desk coordinator openings tied to the newest clinic.",
      ],
      class: "strong_fit",
      subtype: null,
      fitRank: 1,
      triggerQuality: "strong",
      keyedTrigger: "8th location + front-desk hiring",
      bestContact: "Dana Reyes",
      why: "ICP-true on every axis with the strongest live trigger in the room.",
      contactSet: {
        correct: {
          contactName: "Dana Reyes",
          contactTitle: "Director of Operations",
          department: "Operations",
          gender: "female",
        },
        traps: [
          {
            contactName: "Marcus Webb",
            contactTitle: "VP of Finance",
            department: "Finance",
            gender: "male",
            strongerAxis: "seniority — VP outranks Director",
            weakerAxis:
              "wrong department — Finance doesn't own scheduling tooling decisions",
          },
          {
            contactName: "Priya Shah",
            contactTitle: "Front Desk Lead",
            department: "Operations",
            gender: "female",
            strongerAxis:
              "closest to the daily pain, same department — operations relevance",
            weakerAxis: "no purchasing authority to approve a vendor tool",
          },
        ],
      },
    },
    {
      companyName: "BrightSmile Dental Partners",
      vertical: "dental",
      locations: 6,
      metro: "Denver, CO",
      inTerritory: true,
      sizeNote: "6 locations, stable footprint since last expansion",
      onlineBooking: false,
      blurb: "Established dental group with steady multi-site operations in Denver.",
      publicSignals: [
        "Expanded to current size about two years ago",
        "No recent location openings reported",
        "Routine hiring for hygienists only",
      ],
      researchFacts: [
        "Staff have mentioned wanting better software, but no budget has been allocated.",
        "Operations notes from a trade meetup describe scheduling as 'under control' after the last expansion.",
        "Google reviews mention friendly hygienists with no recent scheduling complaints.",
      ],
      class: "near_miss",
      subtype: "no_strain",
      fitRank: null,
      triggerQuality: "weak",
      keyedTrigger: "Stale expansion from two years ago",
      bestContact: "Jordan Alvarez",
      why: "Passes firmographics but lacks a live operational trigger.",
      contactSet: {
        correct: {
          contactName: "Jordan Alvarez",
          contactTitle: "Office Manager",
          department: "Operations",
          gender: "female",
        },
        traps: [
          {
            contactName: "Wei Zhang",
            contactTitle: "VP of Finance",
            department: "Finance",
            gender: "male",
            strongerAxis: "seniority — VP title looks more impressive than Office Manager",
            weakerAxis:
              "wrong department — Finance is not the buyer for scheduling operations tooling",
          },
          {
            contactName: "Fatima Hassan",
            contactTitle: "Front Desk Lead",
            department: "Operations",
            gender: "female",
            strongerAxis:
              "department relevance — same operations team closest to scheduling pain",
            weakerAxis: "far lower seniority — cannot authorize a new vendor",
          },
        ],
      },
    },
    {
      companyName: "Northview Family Dentistry",
      vertical: "dental",
      locations: 3,
      metro: "Boulder, CO",
      inTerritory: true,
      sizeNote: "3 locations in Boulder County",
      onlineBooking: true,
      blurb: "Family dentistry practice with a mature patient base and digital front desk tools.",
      publicSignals: [
        "Markets online self-scheduling on the website",
        "Steady Google review volume with no scheduling complaints",
        "Recently refreshed patient portal branding",
      ],
      researchFacts: [
        "Patient forum threads praise the refreshed portal branding.",
        "Local newsletter profiled the practice's school outreach program.",
        "Website highlights same-day emergency appointment availability.",
      ],
      trapDisqualifierFact:
        "Operations team standardized on SlotEasy eighteen months ago with a multi-year agreement.",
      class: "trap",
      subtype: "already_solved",
      fitRank: null,
      triggerQuality: "weak",
      keyedTrigger: "Portal refresh marketing push",
      bestContact: "Rachel Chen",
      why: "Looks like a clean dental fit on size and territory; disqualifier is an incumbent tool in research.",
      contactSet: {
        correct: {
          contactName: "Rachel Chen",
          contactTitle: "Practice Manager",
          department: "Operations",
          gender: "female",
        },
        traps: [
          {
            contactName: "Diego Morales",
            contactTitle: "VP of Finance",
            department: "Finance",
            gender: "male",
            strongerAxis: "seniority — VP outranks Practice Manager on paper",
            weakerAxis:
              "wrong department — Finance does not own day-to-day scheduling decisions",
          },
          {
            contactName: "Amara Okonkwo",
            contactTitle: "Front Desk Lead",
            department: "Operations",
            gender: "female",
            strongerAxis:
              "operations department relevance — lives the appointment-booking friction daily",
            weakerAxis: "no budget authority despite being closest to the pain",
          },
        ],
      },
    },
    {
      companyName: "Golden State Dental Alliance",
      vertical: "dental",
      locations: 12,
      metro: "Colorado Springs, CO",
      inTerritory: true,
      sizeNote: "12 locations after recent consolidation",
      onlineBooking: false,
      blurb: "Large regional dental alliance with centralized back-office controls.",
      publicSignals: [
        "Recently reduced administrative staff as part of a cost-cutting initiative",
        "Hiring freeze on non-clinical roles announced in a local newsletter",
        "Leadership emphasizing margin protection in a staff memo excerpt",
      ],
      researchFacts: [
        "Google reviews praise friendly hygienists at most locations.",
        "Careers page lists hygienist openings at two locations.",
        "Local newsletter profiled the group's community outreach program.",
        "Website highlights same-day emergency appointment availability.",
      ],
      trapDisqualifierFact:
        "Internal memo leaked to a trade blog cites a freeze on discretionary vendor projects through next fiscal year.",
      class: "trap",
      subtype: "contracting",
      fitRank: null,
      triggerQuality: "strong",
      keyedTrigger: "Administrative staff reduction headline",
      bestContact: "Miguel Torres",
      why: "Passes ICP axes and looks urgent, but hidden research shows contracting spend posture.",
      contactSet: {
        correct: {
          contactName: "Miguel Torres",
          contactTitle: "Practice Manager",
          department: "Operations",
          gender: "male",
        },
        traps: [
          {
            contactName: "Elena Kowalski",
            contactTitle: "VP of Finance",
            department: "Finance",
            gender: "female",
            strongerAxis: "seniority — VP of Finance outranks Practice Manager",
            weakerAxis:
              "wrong department — cost-cutting finance lead is the wrong owner for scheduling tooling",
          },
          {
            contactName: "Caleb Nguyen",
            contactTitle: "Front Desk Lead",
            department: "Operations",
            gender: "male",
            strongerAxis:
              "department relevance — operations front-line role matching the core pain area",
            weakerAxis:
              "insufficient seniority — cannot green-light a multi-location vendor purchase",
          },
        ],
      },
    },
  ],
  targetTriggerSignatureThemes: TARGET_TRIGGER_SIGNATURE_THEMES,
  researchFactsByVertical: MERGED_RESEARCH_FACTS_BY_VERTICAL,
  publicSignalsByVertical: PUBLIC_SIGNALS_BY_VERTICAL,
  publicSignalsByTrapSubtype: PUBLIC_SIGNALS_BY_TRAP_SUBTYPE,
  disqualifierKeywordsByTrapSubtype: DISQUALIFIER_KEYWORDS_BY_TRAP_SUBTYPE,
  trapDisqualifierVariantsBySubtype: TRAP_DISQUALIFIER_VARIANTS_BY_SUBTYPE,
  structuralCorrelation: TEMPO_STRUCTURAL_CORRELATION,
  verticalPool: [
    "dental",
    "veterinary",
    "physical therapy",
    "optometry",
    "med spa",
    "chiropractic",
  ],
  metroPoolInTerritory: [
    "Denver, CO",
    "Front Range, CO",
    "Boulder, CO",
    "Fort Collins, CO",
    "Colorado Springs, CO",
    "Salt Lake City, UT",
    "Boise, ID",
    "Albuquerque, NM",
    "Cheyenne, WY",
    "Missoula, MT",
  ],
  metroPoolOutOfTerritory: [
    "Phoenix, AZ",
    "Seattle, WA",
    "Dallas, TX",
    "Chicago, IL",
    "Atlanta, GA",
    "Portland, OR",
    "Nashville, TN",
    "Minneapolis, MN",
  ],
  passVerticalPool: [
    "retail",
    "hospitality",
    "auto repair",
    "legal services",
    "fitness studio",
    "property management",
  ],
  namePrefixPool: [
    "Brightside",
    "Lakeside",
    "Cedar Grove",
    "Riverside",
    "Union Square",
    "Maple",
    "Harbor",
    "Crestview",
    "Fairview",
    "Hillcrest",
    "Parkway",
    "Meadowbrook",
    "Stonebridge",
    "Oakhurst",
    "Ashford",
    "Birchwood",
    "Dunmore",
    "Foxglove",
    "Glenwood",
    "Highpoint",
    "Ironwood",
    "Juniper",
    "Kingsley",
    "Laurelton",
    "Millbrook",
    "Norwood",
    "Pinehurst",
    "Quarry Hill",
    "Redstone",
    "Silverlake",
    "Thornbury",
    "Vista Ridge",
    "Westbrook",
    "Willowmere",
    "Ashgrove",
    "Brookfield",
    "Copperfield",
    "Alder",
    "Beacon",
    "Canyon",
    "Driftwood",
    "Evergreen",
    "Falcon",
    "Granite",
    "Hawthorne",
    "Ivory",
    "Juniper Ridge",
    "Keystone",
    "Larkspur",
    "Mesa",
    "Northgate",
    "Orchard",
    "Prairie",
    "Quail",
    "Ridgeline",
    "Sagebrush",
    "Timberline",
    "Upland",
    "Valencia",
    "Whispering Pines",
    "Yellowstone",
    "Zion",
    "Alpenglow",
    "Bluebird",
    "Cottonwood",
    "Daybreak",
    "Ember",
    "Fireweed",
    "Goldleaf",
    "Hearthstone",
    "Indigo",
    "Jade",
    "Kestrel",
    "Lumen",
    "Mariner",
    "Nighthawk",
    "Osprey",
    "Peregrine",
    "Rainier",
    "Starling",
    "Tanager",
    "Umber",
    "Vireo",
    "Warbler",
    "Xanadu",
    "Yarrow",
    "Zephyr",
  ],
  nameDescriptorPool: [
    "Regional",
    "Metro",
    "Valley",
    "Ridge",
    "Central",
    "Premier",
    "Heritage",
    "Community",
    "Professional",
    "Integrated",
    "Advanced",
    "Family",
    "Coastal",
    "Mountain",
    "Urban",
  ],
  passPrefixPool: [
    "Alpine",
    "Cascade",
    "Desert Sun",
    "Echo",
    "Frontier",
    "Granite Peak",
    "Horizon",
    "Iron Horse",
    "Juniper Creek",
    "Mesa Ridge",
    "North Fork",
    "Outpost",
    "Pioneer",
    "Quartz",
    "Ridgeway",
    "Sage",
    "Timber",
    "Uinta",
    "Vista",
    "Wilderness",
    "Yellowtail",
    "Copper",
    "Driftwood",
    "Ember",
    "Falcon",
    "Granite",
    "Hearth",
    "Indigo",
    "Jade Creek",
    "Lark",
    "Maverick",
    "Nomad",
    "Oasis",
    "Prairie",
    "Quail",
    "Rustic",
    "Sierra",
    "Teton",
    "Upland",
    "Voyager",
    "Wagon",
    "Aspen",
    "Bison",
    "Canyon",
    "Delta",
    "Evergreen",
    "Grizzly",
    "Harborview",
    "Inlet",
    "Monarch",
    "Ponderosa",
    "Redrock",
    "Sangre",
    "Wasatch",
  ],
  suffixByVertical: {
    dental: ["Dental Group", "Family Dentistry", "Dental Care"],
    veterinary: ["Veterinary Partners", "Animal Hospital"],
    "physical therapy": ["Physical Therapy", "Rehab Partners"],
    optometry: ["Eye Care", "Vision Group"],
    "med spa": ["Med Spa", "Aesthetics"],
    chiropractic: ["Chiropractic Center", "Wellness Group"],
  },
  passSuffixByVertical: PASS_SUFFIX_BY_VERTICAL,
  contactTitlePool: [
    "Front Desk Lead",
    "Office Manager",
    "Practice Manager",
    "Operations Coordinator",
    "Director of Operations",
  ],
  contactDepartmentPool: [
    "Operations",
    "Finance",
    "Front Desk",
    "Administration",
    "Clinical",
  ],
  contactTitleSeniorityRank: [
    "Front Desk Lead",
    "Office Manager",
    "Practice Manager",
    "Operations Coordinator",
    "Director of Operations",
    "VP of Finance",
    "Regional Director",
    "Owner",
    "Founder",
  ],
  contactComparableAxes: [
    {
      name: "seniority",
      keywords: ["senior", "seniority", "vp", "director", "title", "authority", "outrank"],
      getValue: (contact, config) =>
        config.contactTitleSeniorityRank.indexOf(contact.contactTitle),
    },
    {
      name: "department_relevance",
      keywords: ["department", "operations", "relevant", "relevance", "pain"],
      getValue: (contact, config) => {
        if (contact.department !== config.corePainDepartment) {
          return 0;
        }
        if (contact.contactTitle === "Front Desk Lead") {
          return 2;
        }
        return 1;
      },
    },
  ],
};
